# Generated by Django 4.0 on 2021-12-23 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='beers',
        ),
        migrations.AddField(
            model_name='brand',
            name='beers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beers.beer'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
