# Generated by Django 4.0 on 2021-12-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20211226_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='ratings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='beer',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
