# Generated by Django 3.2.5 on 2021-12-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_beer_ratings_beer_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/')),
            ],
        ),
        migrations.AlterField(
            model_name='beer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
