# Generated by Django 4.0 on 2021-12-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_beer_ratings_beer_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
