# Generated by Django 3.2.5 on 2022-01-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_auto_20211229_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='srp',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
