# Generated by Django 3.2.5 on 2021-12-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_alter_beer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
