# Generated by Django 3.2.5 on 2022-01-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_alter_beer_srp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='ratings',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
