# Generated by Django 3.2.5 on 2021-12-29 12:19

import beers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_beer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=beers.models.filePath),
        ),
    ]
