# Generated by Django 3.2.5 on 2022-01-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0009_alter_beer_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
