# Generated by Django 3.2.5 on 2022-01-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0010_beer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
