# Generated by Django 3.2.5 on 2022-01-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0011_alter_beer_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
