# Generated by Django 3.2.5 on 2022-01-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0012_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='srp',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
